name: build_v24
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - patches-argo-cd-v2.4/**
      - patches-gitops-engine/**
      - VERSION_24
      - .github/workflows/build_v24.yaml

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install stgit
        shell: bash
        run: |
          sudo apt-get install -y stgit
          git config --global user.name "Chanwit Kaewkasi"
          git config --global user.email "chanwit@gmail.com"
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Prepare
        id: prep
        run: |
          VERSION="${{ steps.branch-name.outputs.current_branch }}-${GITHUB_SHA::8}"
          echo ::set-output name=VERSION::${VERSION}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build v2.4
        run: |
          ln -s VERSION_24 VERSION
          ln -s patches-argo-cd-v2.4 patches-argo-cd
          ln -s patches-gitops-engine-v0 patches-gitops-engine
          rm -rf argo-cd || true
          bash -x ./init.sh
          source ./VERSION
          VERSION=${BASE_VERSION}-${SUFFIX_VERSION}-${{ steps.prep.outputs.VERSION }}
          ( cd argo-cd && IMAGE_NAMESPACE=ghcr.io/flux-subsystem-argo/fsa IMAGE_TAG=$VERSION DOCKER_PUSH=true make image )
          unlink patches-argo-cd
          unlink VERSION
